### ISSUE TITLE
migrate to the new backend

### ISSUE THREAD

**Issue by nia-potato** [kode3tech/k3t-backstage-plugin-scaffolder-backend-module-plus#1]
Hi @alansferreira  thanks for the great plugin, i was wondering if we can migrate to the new backend?

**Comment by alansferreira** [comment]
Hi, @nia-potato, i think yes, I'm little busy in last days. i will open discussion with our team.

**Comment by alansferreira** [comment]
Hi, @nia-potato! I hope you fine! We release a new version **1.5.6**, compatible with **new backend architecture**.

just 
```bash
yarn add @k3tech/backstage-plugin-scaffolder-backend-module-plus
```
and import module on backend

`packages/backend/src/index.ts`
```ts
...
backend.add(import('@k3tech/backstage-plugin-scaffolder-backend-module-plus'));

```

you can check if all actions and examples in is ready on http://localhost:3000/create/actions

**Comment by nia-potato** [comment]
Thanks!
